#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'hello_world',
  :git => 'https://github.com/flaccid/cookbooks',
  :path => 'cookbooks/hello_world',
  :ref => 'master'